version: "3"
services:
  app:
    container_name: docker-node-mongo
    # restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
